spring:
  application:
    name: consumer-service
  boot:
    admin:
      url: http:localhost:8585
server:
  port: 8081
management:
  security:
    enabled: false

#feign:
#    hystrix:
#        enabled: true